---
apiVersion: v1
kind: Service
metadata:
  name: clickhouse-1
spec:
  type: ClusterIP
  ports:
    - port: 8123
      name: server
    - port: 9000
      name: client
    - port: 9009
      name: interserver
  selector:
    app: clickhouse
    clicknode: "1"
