---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: clickhouse-0
  labels:
    exporter: clickhouse
    clicknode: "0"
spec:
  serviceName: clickhouse-0
  replicas: 1
  template:
    metadata:
      labels:
        app: clickhouse
        exporter: clickhouse
        clicknode: "0"
      annotations:
        pod.alpha.kubernetes.io/initialized: "true"
    spec:
      containers:
        - name: k8sch
          imagePullPolicy: Always
          image: xds2000/clickhouse-server
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: KUBERNETES_DOMAIN
              value: "svc.cluster.local"
            - name: CLUSTER_NAME
              value: "bitbook-servie"
            - name: NODE_ID
              value: "0"
          ports:
            - containerPort: 8123
              name: server
            - containerPort: 9000
              name: client
            - containerPort: 9009
              name: interserver
        - name: clickhouse-exporter
          image: f1yegor/clickhouse-exporter
          ports:
            - containerPort: 9116
