---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: clickhouse-3
  labels:
    exporter: clickhouse
    clicknode: "3"
spec:
  serviceName: clickhouse-3
  replicas: 1
  template:
    metadata:
      labels:
        app: clickhouse
        exporter: clickhouse
        clicknode: "3"
      annotations:
        pod.alpha.kubernetes.io/initialized: "true"
    spec:
      containers:
        - name: k8sch
          imagePullPolicy: Always
          image: count0ru/k8s-clickhouse-v2
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: KUBERNETES_DOMAIN
              value: "svc.cluster.local"
            - name: CLUSTER_NAME
              value: "bitbook-service"
            - name: NODE_ID
              value: "3"
          ports:
            - containerPort: 8123
              name: server
        - name: clickhouse-exporter
          image: f1yegor/clickhouse-exporter
          ports:
            - containerPort: 9116
