---
apiVersion: v1
kind: Service
metadata:
  name: clickhouse-0
spec:
  type: ClusterIP
  ports:
    - port: 8123
      name: server
    - port: 9000
      name: client
  selector:
    app: clickhouse
    clicknode: "0"
